#! /usr/bin/env bash

# Stop the script if an operation fails
set -e

node_modules/typescript/bin/tsc --outDir .tmp/unit-tests

node_modules/mocha/bin/mocha -r jsdom-global/register .tmp/unit-tests/**/*.spec.js

rm -rf .tmp/unit-tests
